<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Athena Randomizer v0.17</AssemblyName>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Resources\Assets\Athena.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\dependencies\EldenRingParamsEditor\EldenRingParamsEditor\EldenRingParamsEditor.csproj" />
		<ProjectReference Include="..\dependencies\UniversalReplacementRandomizer\UniversalReplacementRandomizer\UniversalReplacementRandomizer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Misc\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\me3-v0.8.0\**\*.dcx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<!--<Content Include="Resources\me3-v0.8.0\**\*.tpfbdt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\me3-v0.8.0\**\*.tpfbhd">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>-->
		<Content Include="Resources\me3-v0.8.0\**\*.bat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\me3-v0.8.0\**\*.me3">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\me3-v0.8.0\bin\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\me3-v0.8.0\StutterFix\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\RandomizationGroups\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\GameData\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\Regulation\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\Bnd\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<None Remove="Resources\Assets\Athena.ico" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_anamnesis\common.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_anamnesis\common_func.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_anamnesis\m10_01_00_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_anamnesis\m11_10_00_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_anamnesis\m61_46_40_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_default\common.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_default\common_func.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_default\m10_01_00_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_default\m11_10_00_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\event_default\m61_46_40_00.emevd.dcx" />
		<None Remove="Resources\me3-v0.8.0\dlc\menu_anamnesis\05_001_title_logo.gfx" />
		<Content Include="oo2core_6_win64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
		<Content Include="Resources\Assets\Athena.ico" />
		<Content Include="Resources\me3-v0.8.0\dlc\menu_anamnesis\05_001_title_logo.gfx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="CsvHelper" Version="33.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Bnd\base\" />
	  <Folder Include="Resources\ModEngine-2.1.0.0-win64\base\msg\engus\" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Assets\Athena.ico" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_anamnesis\common.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_anamnesis\common_func.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_anamnesis\m10_01_00_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_anamnesis\m11_10_00_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_anamnesis\m61_46_40_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_default\common.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_default\common_func.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_default\m10_01_00_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_default\m11_10_00_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\event_default\m61_46_40_00.emevd.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\menu_anamnesis\hi\01_common.tpf.dcx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Resources\me3-v0.8.0\dlc\menu_anamnesis_src\hi\01_common.tpf.dcx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\me3-v0.8.0\dlc\menu_anamnesis_src\05_001_title_logo.gfx">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>